version: '3.7'

x-shared_environment: &shared_environment
  BASEIMAGE: ${BASEIMAGE}
  IMAGE: ${IMAGE}
  SCRIPT_DIR: ${SCRIPT_DIR}
  FOLDER: ${FOLDER}

x-shared_job: &shared_job
  image: ${IMAGE}:${VERSION}
  privileged: true
  build:
    context: ${SCRIPT_DIR}
    dockerfile: deployment/Dockerfile
    args:
      <<: *shared_environment
  environment:
    <<: *shared_environment
  volumes:
    - ./Sources:/build

services:

  codebook:
    <<: *shared_job
    ports:
      - "8080:31546"
    volumes:
      - ${FOLDER}:/project
      - ./settings.json:/root/.local/share/code-server/User/settings.json