version: '3.7'

x-shared_environment: &shared_environment
  BASEIMAGE: ${BASEIMAGE}
  IMAGENAME: ${IMAGENAME}
  SCRIPT_DIR: ${SCRIPT_DIR}

x-shared_job: &shared_job
  image: ${IMAGENAME}:latest
  privileged: true
  build:
    context: ${SCRIPT_DIR}
    dockerfile: deployment/Dockerfile
    args:
      <<: *shared_environment
  environment:
    <<: *shared_environment
  volumes:
    - ./Sources:/build

services:

  codebook:
    <<: *shared_job
    ports:
      - "8080:31546"
    volumes:
      - ./Project:/project