---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codebook-project
  namespace: codebook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codebook-data
  namespace: codebook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 4Gi
